/**
 * Imperative ocean engine: a world-span water column (four viewport-heights
 * deep), procedural fauna, hook line, and the reel-up catch animation. The
 * camera follows the hook down as context occupancy grows, so one frame shows
 * only the band around the hook — the sea darkens continuously instead of
 * stacking all four zones on screen. Pure canvas code — no React; the
 * component in ocean.tsx drives it through resize/setDepth/bite/resume and a
 * rAF step+draw loop.
 *
 * The engine is split across sibling modules (this file owns state + the
 * small accessors): engine-step.ts (per-tick simulation), engine-catch.ts
 * (claw/auto-catch mechanics), engine-draw.ts + engine-creature-draw.ts
 * (rendering), engine-ambient.ts (pond world + ambient fauna),
 * engine-populate.ts (fauna/bubble population). Members marked
 * "internal:" are shared with those modules — not part of the public
 * contract (tests may still cast-peek them).
 */
import { ZONES } from './depth.ts'
import { Roam } from './roam.ts'
import { makeOceanCreature, type FaunaSprites } from './fauna.ts'
import { hueOf, kindsOf, type OceanProfile } from './oceans.ts'
import { seededDecor } from './decor.ts'
import { stockPondInto, setPondZoomInto, zoomPondInto, clampPondCamera } from './engine-ambient.ts'
import { populateInto, populateBubblesInto, retuneInto } from './engine-populate.ts'
import { closeClawOn, autoWideGrabOn } from './engine-catch.ts'
import { stepEngine } from './engine-step.ts'
import { renderOcean, type DecorItem } from './engine-draw.ts'

export interface Creature {
  zone: number
  /** Pond ambient adds 'shrimp' and 'crab' to the procedural zoo (v44);
    * they have no fauna sprite, no card-spirit mapping, and never appear
    * in the OCEAN fauna pools — the engine draws them with hand-coded
    * side-view silhouettes in drawCreature. */
  kind: 'fish' | 'turtle' | 'hatchet' | 'jelly' | 'viper' | 'squid' | 'angler' | 'octopus' | 'eel' | 'shrimp' | 'crab'
  x: number; y: number; vx: number
  size: number; hue: number; phase: number
  /** Per-card sprite key (pond) — falls back to kind sprite when absent. */
  spriteKey?: string
  /** Optional vertical swimming lane in WORLD px (v44 pond ambient). When
    * set, stepPondCreature clamps the creature's y between these bounds
    * instead of the default full-band clamp — used by shrimp (close to
    * floor), crab (nailed to the soil seam), eel (slightly above floor),
    * and any future posture-specific fauna. Undefined = default band. */
  laneLo?: number
  laneHi?: number
}

interface Bubble { x: number; y: number; r: number; w: number; s: number }

type EngineState = 'idle' | 'reeling' | 'raised'

/** Ocean depth in viewport heights: one viewport ≈ one zone band. */
const WORLD_SPAN = 4

const clamp = (v: number, lo: number, hi: number): number => Math.min(Math.max(v, lo), hi)

export class OceanEngine {
  w = 0; h = 0; dpr = 1
  t = 0
  occupancy = 0
  hookY = 40; hookTargetY = 40
  camY = 0; camTargetY = 0
  /** Pond-mode horizontal camera. Ocean mode always treats this as 0 (the
    * hook patrol never leaves the viewport width). Pond-mode sets it via
    * panPond() so the diver can slide around a multi-screen pond world. */
  camX = 0
  /** Pond world dimensions (world-space px). 0 = no pond world set;
    * stockPond() falls back to the viewport (w×h). Non-zero → the school
    * may live across multiple "screens" and the diver pans with panPond. */
  pondWW = 0
  pondWH = 0
  /** v47: pond view zoom (1 = native). The render transform scales the
    * world around the viewport center (engine-draw.ts); pan and
    * hit-test math divide by it. Ocean mode always renders at 1. */
  pondZoom = 1
  hookX = 0.62
  creatures: Creature[] = []
  /** Pond ambient fauna (v44): tiny unnamed fish / shrimp / crab / eel that
    * populate the world beyond the diver's own catch. Generated by
    * stockPond() at the bottom of the call so React stays unaware; ambient
    * is drawn BEFORE creatures with a soft globalAlpha so it reads as a
    * background population. stepPondCreature handles both lists with the
    * same lane clamp. */
  ambient: Creature[] = []
  bubbles: Bubble[] = []
  state: EngineState = 'idle'
  caught: Creature | null = null
  reelP = 0
  /** Claw openness: 0 = fully open (idle), 1 = fully closed (snapped shut).
    * Animates between the two once closeClaw() fires; reeling/raised pin it
    * to 1 so the claw stays gripped while the fish rides up. */
  clawShut = 0
  /** internal: (engine-catch/step) claw animation timestamps. */
  closeAt = 0
  /** internal: (engine-catch/step) when the claw re-opens. */
  reopenAt = 0
  onCatchStart: ((depth: number, zoneIdx: number, auto: boolean) => void) | null = null
  /** Pond mode: no hook, no catches — the diver's own fish just swim. */
  pondMode = false
  /** v46: pond auto-tour (wander) — when ON, the pond camera slowly
    * cruises to random waypoints inside the world so the diver can see
    * the whole school without dragging. Public so the React layer can
    * pin it directly when needed; `setPondWander` is the preferred
    * path because it also handles the soft-start handoff. */
  pondWander = false
  /** internal: (engine-step) tour target in world coords. Initialized to
    * (0,0) so a freshly-armed engine never crashes on the very first
    * step (the wander block short-circuits until the wander flag flips
    * on). */
  wanderX = 0
  wanderY = 0
  /** internal: (engine-step) time at which the current waypoint is "done"
    * and a new one should be picked. The wander block uses both a
    * distance threshold AND a wall-clock timer (otherwise a target
    * chosen at the same point as the camera would loop forever). */
  wanderNextAt = 0
  /** Session ocean (see oceans.ts): fauna pools, hues, water tint and
    * seabed decor. Null = the historical default tables. */
  ocean: OceanProfile | null = null
  setOcean(profile: OceanProfile): void {
    this.ocean = profile
    this.seabedItems = null // re-derive the decor layout lazily on next draw
    // Repopulate live fauna so an ocean set after the first populate still
    // shows the new mix (resize's first-populate path also honors it).
    if (!this.pondMode && this.w > 0 && this.creatures.length > 0) {
      populateInto(this, (z, f) => this.makeCreature(z, f))
    }
  }
  /** v46: arm / disarm the pond auto-tour. Switching OFF mid-walk just
    * parks the camera where it is; switching ON seeds the waypoint to
    * the current camera and gives the diver a 1.5s grace period before
    * the first random target is picked (so the world doesn't jerk the
    * moment the tour re-engages after a drag). */
  setPondWander(on: boolean): void {
    this.pondWander = on
    if (on) {
      this.wanderX = this.camX
      this.wanderY = this.camY
      this.wanderNextAt = this.t + 1.5
    }
  }
  /** Derived seabed decor layout for the current ocean (x fractions are
    * width-relative, so resizes stay proportional with no bookkeeping). */
  private seabedItems: ReadonlyArray<DecorItem> | null = null
  /** MiniMax-painted sprites (see fauna.ts); null until loaded. Kinds
    * without a sprite keep their procedural drawing. */
  sprites: FaunaSprites | null = null
  setSprites(sprites: FaunaSprites): void { this.sprites = sprites }

  /** Per-kind pool of card spirit ids (v40: ocean fish can wear a real
    * card art). Empty/undefined = no card outfit (falls back to kind
    * sprite). Pond mode ignores this — the pond sets spriteKey itself
    * on every stocked creature, so card-spirit wear would only double up
    * (and pull random ids into a deterministic 1:1 mapping). */
  private cardSpirits: ReadonlyMap<string, ReadonlyArray<string>> = new Map()
  /** Hand the engine a cardKind → ids lookup so freshly-spawned fauna
    * can dress in a random matching card spirit. Picking is unseeded
    * (Math.random) — the OUTER test contract is "new fauna has a
    * spriteKey from the right pool", not "this specific id". Re-stocking
    * existing creatures with the new pool is part of the same call so the
    * screen updates without waiting for the next retune. */
  setCardSpirits(byKind: ReadonlyMap<string, ReadonlyArray<string>>): void {
    this.cardSpirits = byKind
    if (this.pondMode) return // pond fish own their own spriteKey
    for (const c of this.creatures) this.maybeWearCardSpirit(c)
  }
  /** Pick (and stamp) a card-spirit id for one creature when the pool
    * for its kind is non-empty. No-op when the pool is empty (creature
    * stays on the kind sprite) or in pond mode. */
  private maybeWearCardSpirit(c: Creature): void {
    if (this.pondMode) return
    const pool = this.cardSpirits.get(c.kind)
    if (pool === undefined || pool.length === 0) {
      c.spriteKey = undefined
      return
    }
    c.spriteKey = pool[Math.floor(Math.random() * pool.length)]
  }

  /* -- idle roaming: the hook patrols the WHOLE panel (see roam.ts) ----- */
  /** internal: (engine-step) the shared patrol driver. */
  readonly roam = new Roam()
  /** Seconds between collision-triggered catches (busy gate aside). */
  private static readonly CATCH_COOLDOWN = 75
  /** internal: (engine-catch) session-start cooldown clock. Catches are
    * impossible until the engine has been alive for CATCH_COOLDOWN
    * seconds — a fresh page load must NOT insta-catch (the dry-spell
    * luck window also counts from session start, not from -Infinity).
    * Initialized to 0 so closeClaw() reads the session-start gate from
    * lockUntil alone. */
  lastCatchAt = 0
  /** internal: (engine-catch) short local lock gated by markMiss/markCatch
    * — separate from the dry-spell clock (lastCatchAt). A miss immediately
    * resets this so the player can re-grab right away; a catch arms it for
    * CATCH_COOLDOWN seconds so the post-catch world isn't insta-spammable.
    * Seeded to CATCH_COOLDOWN so the very first closeClaw() at t=0 is
    * blocked (the legacy "no instant catch on refresh" behavior). */
  lockUntil = OceanEngine.CATCH_COOLDOWN

  /* -- manual hook control (user pointer steering) ---------------------- *
    * While the pointer moved recently (MANUAL_HOLD seconds), the hook
    * follows it instead of the autonomous patrol. All positions are WORLD
    * coords scaled by the same kx/ky as everything else on resize, so the
    * hook-to-fish geometry invariant holds in manual mode too. */
  /** internal: (engine-catch/step) manual steering state. */
  manual: { x: number, y: number } | null = null
  manualTarget: { x: number, y: number } | null = null
  manualUntil = 0
  /** Seconds the hook keeps following the pointer after the last move. */
  private static readonly MANUAL_HOLD = 4

  /* -- idle auto-catch: the unsteered claw snaps on its own ------------ *
    * While the hook is unsteered (manual === null OR manual hold lapsed)
    * the engine periodically closes the claw via the SAME path the player
    * uses — a slow hands-free drip so the world keeps producing cards
    * even when nobody is steering. OFF by default: tests build engines
    * directly and their long step() runs must not trigger grabs; the
    * React layer opts in on mount via enableAutoCatch(). */
  autoCatch = false
  /** internal: (engine-step) next hands-free attempt time. */
  nextAutoAt = Infinity
  /** internal: (engine-catch/step) true while the CURRENT grab
    * (reeling→raised) was started by the auto-catch timer, not the
    * player — passed to onCatchStart so the UI can stay quiet during
    * cooldowns for automatic grabs. */
  lastGrabAuto = false
  /** internal: (engine-catch) connect probability for one hands-free
    * attempt (the "does the claw find anything" roll before the wide
    * sweep). Field (not a literal) so tests can pin it to 0/1 for
    * deterministic coverage of both branches. */
  autoConnectRate = 0.8

  /** Feed a pointer position in VIEWPORT px — starts/refreshes manual
    * control. No-op in pond mode (no hook there). */
  pointerTo(vx: number, vy: number): void {
    if (this.pondMode || this.w === 0) return
    if (this.manual === null) {
      const hp = this.hookPos()
      this.manual = { x: hp.x, y: hp.y }
    }
    this.manualTarget = { x: vx, y: vy + this.camY }
    this.manualUntil = this.t + OceanEngine.MANUAL_HOLD
  }

  /** Where the hook actually is right now (manual follow, or the patrol).
    * Public read accessor — tests and the HUD can observe the hook. */
  hookPos(): { x: number, y: number } {
    if (this.manual !== null && this.manualTarget !== null && this.t <= this.manualUntil) {
      return { x: this.manual.x, y: this.manual.y }
    }
    return this.roam.pos({ w: this.w, h: this.h, camY: this.camY })
  }

  /** World depth in canvas px (viewport height × span).
    * internal: engine-step scales the camera clamp with it. */
  get worldH(): number { return this.h * WORLD_SPAN }

  resize(w: number, h: number, dpr: number): void {
    // Degenerate-size guard: when the float window is minimized the host
    // hides the content box (right:-9999, visibility:hidden → height 0),
    // ResizeObserver then calls resize with a collapsed rect. NaN, zero,
    // and negative dimensions are all degenerate — no-op so the engine
    // keeps its last valid size + world state (fish, hook, camera, roam,
    // manual). On restore the next non-degenerate resize runs the normal
    // prevWorld>0 branch with prevW/prevWorld = the LAST valid pair, so
    // kx/ky are computed against real geometry and the fish survive the
    // round trip. This also guards a plugin mounted into a hidden host
    // whose first resize is already 0×0 (populate would otherwise squeeze
    // every fish into the 10px band).
    if (!(w > 0) || !(h > 0)) return
    const prevW = this.w; const prevWorld = this.worldH
    const first = this.w === 0
    this.w = w; this.h = h; this.dpr = dpr
    if (!this.pondMode && (first || this.creatures.length === 0)) {
      populateInto(this, (z, f) => this.makeCreature(z, f))
      populateBubblesInto(this)
      this.hookY = this.hookTargetY = this.h * 0.08
      this.roam.seed(this.hookX * this.w, this.hookY)
      this.camY = this.camTargetY = 0
    } else if (prevWorld > 0 && (w !== prevW || this.worldH !== prevWorld)) {
      // Keep everyone at the same RELATIVE spot when the window resizes:
      // fish, bubbles, hook patrol and camera all scale by the same width
      // and height ratios, so hook-to-fish geometry is preserved exactly.
      // v44 also scales the ambient fauna (and their lane clamps) so the
      // shrimp/crab/eel lane proportions survive the resize.
      const kx = w / prevW; const ky = this.worldH / prevWorld
      for (const c of this.creatures) { c.x *= kx; c.y *= ky }
      for (const c of this.ambient) {
        c.x *= kx; c.y *= ky
        if (c.laneLo !== undefined) c.laneLo *= ky
        if (c.laneHi !== undefined) c.laneHi *= ky
      }
      for (const b of this.bubbles) { b.x *= kx; b.y *= ky }
      this.hookY *= ky; this.hookTargetY *= ky
      this.camY *= ky; this.camTargetY = clamp(this.hookTargetY - this.h * 0.38, 0, this.worldH - this.h)
      this.roam.scale(kx, ky)
      // Manual-control state lives in world coords too — same ratios.
      if (this.manual !== null) { this.manual.x *= kx; this.manual.y *= ky }
      if (this.manualTarget !== null) { this.manualTarget.x *= kx; this.manualTarget.y *= ky }
    }
    // Pond world: re-clamp the pond camera now that the viewport may
    // have changed — otherwise the camera could end up parked past the
    // right/bottom edge and show void. We do NOT scale pondWW/pondWH
    // here; the React layer re-derives the world from the new viewport
    // in pondWorldFor() and re-stocks, which resets the camera too.
    // This clamp is a safety net for the brief window between resize
    // and restock (creatures get kx/ky-scaled above; world bounds stay
    // put so the clamp is consistent with the restock that follows).
    // v47: the visible span is zoom-aware, so clamp with the shared
    // helper instead of the raw viewport dims.
    if (this.pondMode && this.pondWW > 0 && this.pondWH > 0) {
      clampPondCamera(this)
    }
  }

  /** World-px depth band of a zone (bands tile the world span, not the
    * viewport). internal: shared with engine-step / engine-catch. */
  zoneBand(zone: number): [number, number] {
    const z = ZONES[zone]
    const top = (zone === 0 ? 0.02 : (z?.lo ?? 0) + 0.01) * this.worldH
    const bottom = ((z?.hi ?? 1) - 0.01) * this.worldH
    return [top, Math.max(bottom, top + 10)]
  }

  private makeCreature(zone: number, yFrac?: number): Creature {
    const [ylo, yhi] = this.zoneBand(zone)
    const c = makeOceanCreature(zone, this.w, ylo, yhi, hueOf(this.ocean, zone), yFrac,
      this.ocean === null ? undefined : kindsOf(this.ocean, zone))
    // v40: dress ocean fauna in a matching card spirit when one is in
    // the pool. Pond creatures (stocked pre-emptively) already have their
    // own spriteKey, so the helper is a no-op for them.
    this.maybeWearCardSpirit(c)
    return c
  }

  /** Pond mode: adopt prebuilt creatures (see pondStock in pond.tsx) —
    * the diver's own catch, no hook, no catches while it is on. When
    * `worldW` / `worldH` are supplied the school lives in a virtual pond
    * larger than the viewport (fish wrap and pan on world-sized bounds);
    * without them the legacy viewport pond behavior is kept. The state
    * loading lives in engine-ambient.ts (stockPondInto). */
  stockPond(creatures: ReadonlyArray<Creature>, worldW?: number, worldH?: number): void {
    stockPondInto(this, creatures, worldW, worldH)
  }

  /** v47: set the pond zoom absolutely (clamped to [0.5, 2.5]); the
    * camera re-clamps to the zoom-aware world bounds. Body lives in
    * engine-ambient.ts (setPondZoomInto). */
  setPondZoom(z: number): void {
    setPondZoomInto(this, z)
  }

  /** v47: pointer-anchored zoom — multiply the zoom by `factor` while
    * keeping the world point under viewport coords (vx, vy) pinned to
    * that anchor (the natural wheel-zoom feel). Body: engine-ambient.ts
    * (zoomPondInto). */
  zoomPond(vx: number, vy: number, factor: number): void {
    zoomPondInto(this, vx, vy, factor)
  }

  /** Shift the pond camera by a world-pixel delta (positive = move camera
    * to the right, revealing leftward content). Deltas arrive as SCREEN
    * px from the React layer and are divided by the zoom so content
    * tracks the pointer 1:1 at every zoom level. v49: bounds come from
    * pondCamBounds (center-anchored zoom semantics — the camera may go
    * negative when zoomed in so the world's top-left stays reachable),
    * and a no-world pond pans within its viewport-sized world too. */
  panPond(dx: number, dy: number): void {
    if (!this.pondMode) return
    this.camX += dx / this.pondZoom
    this.camY += dy / this.pondZoom
    clampPondCamera(this)
  }

  /** Convert a viewport-pixel point into world-pixel coordinates — the
    * exact inverse of the draw transform (world = cam + center +
    * (screen − center)/zoom). Hit-testing uses this so clicks always
    * land on the fish the player can actually see, at any zoom or pan. */
  screenToWorld(vx: number, vy: number): { x: number, y: number } {
    const z = this.pondZoom
    return {
      x: this.camX + this.w / 2 + (vx - this.w / 2) / z,
      y: this.camY + this.h / 2 + (vy - this.h / 2) / z,
    }
  }

  /** Shift population toward the hook's zone (deeper context → deeper
    * fauna). Body lives in engine-populate.ts (retuneInto). */
  retune(zoneIdx: number): void {
    retuneInto(this, (z, f) => this.makeCreature(z, f), zoneIdx)
  }

  setDepth(occ: number): void {
    this.occupancy = occ
    this.hookTargetY = 0.03 * this.worldH + occ * 0.93 * this.worldH
  }

  /** internal: (engine-catch) lane fraction of the currently caught fish —
    * recorded at bite time (before the reel moves it) so the REPLACEMENT
    * creature resumes() into the same depth lane. Keeps the stratified
    * spread stable even under back-to-back catching; without it every
    * catch respawns one fish at a random depth and the population drifts
    * into plane clumps. */
  caughtFrac: number | null = null

  /** Snap the claw shut on the nearest creature within the claw radius —
    * the manual catch. Deterministic; returns true on a real grab, false
    * on an empty clap (or any gate it short-circuits on). Body lives in
    * engine-catch.ts (closeClawOn). */
  closeClaw(): boolean {
    return closeClawOn(this)
  }

  /** Legacy name kept for older tests + callers — now an alias for
    * closeClaw(). */
  bite(): boolean {
    return this.closeClaw()
  }

  /** internal: wide-sweep bite for the hands-free drip (kept as a method —
    * hook-ride.spec calls it through a cast). Body: engine-catch.ts
    * (autoWideGrabOn). */
  autoWideGrab(): boolean {
    return autoWideGrabOn(this)
  }

  /** Miss outcome (no card generated): arm a SHORT RANDOM re-grab lock
    * (8–20s) so a wriggled fish can't be re-grabbed instantly — the
    * escape→re-grab→escape spam loop reads as "always catchable" (user
    * feedback). The pity clock (lastCatchAt) is untouched so consecutive
    * misses keep widening the dry-spell radius. Network failures share
    * this lock (same anti-spam rationale). */
  markMiss(): void { this.lockUntil = this.t + 8 + Math.random() * 12 }

  /** Success outcome (a card was minted): advance the pity clock so the
    * dry-spell radius resets, and re-arm the short local lock for
    * CATCH_COOLDOWN seconds so post-catch spamming is impossible. */
  markCatch(): void {
    this.lastCatchAt = this.t
    this.lockUntil = this.t + OceanEngine.CATCH_COOLDOWN
  }

  resume(): void {
    if (this.caught !== null) {
      const idx = this.creatures.indexOf(this.caught)
      if (idx >= 0 && this.creatures[idx] !== undefined) {
        // Same lane, fresh fish — the stratified spread never drifts.
        this.creatures[idx] = this.makeCreature(this.caught.zone, this.caughtFrac ?? undefined)
      }
    }
    this.caught = null; this.caughtFrac = null; this.state = 'idle'
    // Reset the claw pose so the post-catch world starts open again.
    this.clawShut = 0
    this.closeAt = 0
    this.reopenAt = 0
    // Drop any stale manual steering — the catch flow took seconds, so the
    // old pointer target no longer means anything. Patrol resumes from the
    // depth anchor; moving the pointer re-takes control instantly.
    this.manual = null
    this.manualTarget = null
    // Roam: resume near the depth anchor, then pick a fresh patrol point.
    this.roam.seed(this.hookX * this.w, this.hookY)
    this.setDepth(this.occupancy)
  }

  /** Enable hands-free auto-catch (called once on mount by the React
    * layer). The first automatic grab lands ~40s later — long enough to
    * not race the player's manual attempts, short enough to feel like
    * the world keeps producing. Disabled by default so tests that build
    * engines directly and drive them with long step() runs never trigger
    * an unintended grab. */
  enableAutoCatch(): void {
    this.autoCatch = true
    if (this.nextAutoAt === Infinity) this.nextAutoAt = this.t + 40
  }

  /** One simulation tick. Body lives in engine-step.ts (stepEngine). */
  step(dt: number): void {
    stepEngine(this, dt)
  }

  /** Paint one frame. Body lives in engine-draw.ts (renderOcean); the
    * lazy seabed decor memo stays engine-owned (setOcean resets it). */
  draw(ctx: CanvasRenderingContext2D): void {
    renderOcean(ctx, this, this.worldH, () => {
      if (this.seabedItems === null) this.seabedItems = seededDecor(this.ocean as OceanProfile)
      return this.seabedItems
    })
  }
}
